return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   opts = function(_, opts)
  --     -- add tsx and treesitter
  --     vim.list_extend(opts.ensure_installed, {
  --       "tsx",
  --       "typescript",
  --     })
  --   end,
  --
  --   config = function()
  --     require("nvim-treesitter.configs").setup({
  --       ensure_installed = { "markdown", "markdown_inline", "sql" },
  --       highlight = {
  --         enable = true,
  --       },
  --     })
  --     -- MDX
  --     vim.filetype.add({
  --       extension = {
  --         mdx = "mdx",
  --       },
  --     })
  --     vim.treesitter.language.register("markdown", "mdx")
  --   end,
  -- },
}
